=head1 C++ SDKD Implementation

This is the libcouchbase-based sdkd implementation in C++, it utilizes
C<libcouchbase> to perform SDK operations.

It requires libcouchbase
headers and JsonCPP. On debian systems you may install it via apt:

    sudo apt-get install libjsoncpp0 libjsoncpp-dev

Then

    make -C cplusplus CXX=g++

To run the C++/libcouchbase C<sdkd>

    ./cbsdk_client -C conf/lcb.cfg < ... options ... >


For OS X systems, the build process is slightly more complex.. here is
a log of my session:

    mbp:src mnunberg$ git clone https://github.com/mrtazz/json-cpp.git
    mbp:src mnunberg$ cd json-cpp/
    mbp:json-cpp mnunberg$ make -f makefiles/gcc/Makefile staticlibrary
    
    # Now that we've built jsoncpp, go in to the main directory
    
    mbp:json-cpp mnunberg$ cd ~/src/sdkd-cpp/
    mbp:sdkd-cpp mnunberg$ make -C src/ JSONCPP_CPPFLAGS=-I$HOME/src/json-cpp/include JSONCPP_LFLAGS=~/src/json-cpp/lib/libjson-cpp.a
