all: main sdkd_lcb

contrib/debug.o: contrib/debug.c
	$(CC) $(CPPFLAGS) -c -g -o $@ $^

%.o: %.cpp
	$(CXX) -c $(CPPFLAGS) -o $@ $^

main: main.cpp $(OBJECTS)
	$(CXX) $(CPPFLAGS) -o $@ $^ $(LDFLAGS)

sdkd_lcb: sdkd_lcb.cpp $(OBJECTS)
	$(CXX) $(CPPFLAGS) -o $@ $^ $(LDFLAGS)

clean:
	rm -f $(OBJECTS) sdkd_lcb main
