all: main sdkd_lcb

BINLFLAGS := -L$(shell pwd) -Wl,-rpath='$$ORIGIN' -lcbsdkd
SOLIB=libcbsdkd.so

$(SOLIB): $(OBJECTS)
	$(CXX) -shared -o $@ $^ $(LDFLAGS)

main: main.cpp $(SOLIB)
	$(CXX) -o $@ $(CPPFLAGS) $< $(BINLFLAGS) $(LDFLAGS)

%.o: %.cpp
	$(CXX) -fPIC -c -o $@ $^ $(CPPFLAGS)

contrib/debug.o: contrib/debug.c
	$(CC) -g -fPIC -c -o $@ $^

sdkd_lcb: sdkd_lcb.cpp $(SOLIB)
	$(CXX) -o $@ $(CPPFLAGS) $< $(BINLFLAGS) $(LDFLAGS)

clean:
	rm -f main $(OBJECTS) *.so *.o main sdkd_lcb
